name: Github Action Label Create Demo
run-name: ${{ github.actor }} is playing with Github Action on props
on:
  label:
    types:
      - created
      - edited
jobs:
  Explorer-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
